### ISSUE TITLE
Do you use "fuse" optimization?

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/benchmark#39]
To complete the optimization pipeline I adapted [opeo-maven-plugin](https://github.com/objectionary/opeo-maven-plugin) to make `fuse` optimization possible. I even added [the integration test](https://github.com/objectionary/opeo-maven-plugin/tree/master/src/it/benchmark) for the `fuse` optimization. 
But as I see, you don't use `fuse` optimization anymore. Is it correct?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please?

**Comment by yegor256** [comment]
@volodya-lombrozo we use `ineo:staticize` now, not `fuse`, because `fuse` doesn't produce any performance effect

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you
